import { NextResponse } from 'next/server'
import { createServerClient } from '@supabase/ssr'
import { cookies } from 'next/headers'
import type { CookieOptions } from '@supabase/ssr'
import { addSubdomain } from '@/lib/vercel'
import type { Database } from '@/types/supabase'
import type { OnboardingState } from '@/components/onboarding/OnboardingFlow'

export async function POST(request: Request) {
  try {
      const body = (await request.json()) as OnboardingState
          const { account, community, branding, members } = body

              // Validate required fields
                  if (!account.userId) {
                        return NextResponse.json({ error: 'Missing auth user ID. Please complete step 1.' }, { status: 400 })
                            }
                                if (!community.slug || !community.communityName) {
                                      return NextResponse.json({ error: 'Missing community name or slug.' }, { status: 400 })
                                          }

                                              const cookieStore = await cookies()
                                                  const supabase = createServerClient<Database>(
                                                        process.env.NEXT_PUBLIC_SUPABASE_URL!,
                                                              process.env.SUPABASE_SERVICE_ROLE_KEY!,
                                                                    {
                                                                            cookies: {
                                                                                      getAll() {
                                                                                                  return cookieStore.getAll()
                                                                                                            },
                                                                                                                      setAll(cookiesToSet: { name: string; value: string; options: CookieOptions }[]) {
                                                                                                                                  cookiesToSet.forEach(({ name, value, options }) =>
                                                                                                                                                cookieStore.set(name, value, options),
                                                                                                                                                            )
                                                                                                                                                                      },
                                                                                                                                                                              },
                                                                                                                                                                                    },
                                                                                                                                                                                        )

                                                                                                                                                                                            // 1. Check slug availability one last time
                                                                                                                                                                                                const { data: existing } = await supabase
                                                                                                                                                                                                      .from('tenants')
                                                                                                                                                                                                            .select('id')
                                                                                                                                                                                                                  .eq('slug', community.slug)
                                                                                                                                                                                                                        .maybeSingle()

                                                                                                                                                                                                                            if (existing) {
                                                                                                                                                                                                                                  return NextResponse.json(
                                                                                                                                                                                                                                          { error: `The slug "${community.slug}" was just taken. Please go back and choose another.` },
                                                                                                                                                                                                                                                  { status: 409 },
                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                // 2. Insert tenant
                                                                                                                                                                                                                                                                    const { data: tenant, error: tenantError } = (await supabase
                                                                                                                                                                                                                                                                          .from('tenants')
                                                                                                                                                                                                                                                                                .insert({ slug: community.slug, name: community.communityName, custom_domain: null })
                                                                                                                                                                                                                                                                                      .select('id')
                                                                                                                                                                                                                                                                                            .single()) as { data: { id: number } | null; error: unknown }

                                                                                                                                                                                                                                                                                                if (tenantError || !tenant) {
                                                                                                                                                                                                                                                                                                      console.error('[onboarding] tenant insert error:', tenantError)
                                                                                                                                                                                                                                                                                                            return NextResponse.json({ error: 'Failed to create community. Please try again.' }, { status: 500 })
                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                    const tenantId = tenant.id

                                                                                                                                                                                                                                                                                                                        // 3. Insert tenant_config rows
                                                                                                                                                                                                                                                                                                                            const configRows = [
                                                                                                                                                                                                                                                                                                                                  { tenant_id: tenantId, key: 'tagline', value: community.tagline || null },
                                                                                                                                                                                                                                                                                                                                        { tenant_id: tenantId, key: 'color_ruby', value: branding.primaryColor },
                                                                                                                                                                                                                                                                                                                                              { tenant_id: tenantId, key: 'color_blush', value: branding.secondaryColor },
                                                                                                                                                                                                                                                                                                                                                  ]
                                                                                                                                                                                                                                                                                                                                                      const { error: configError } = await supabase.from('tenant_config').insert(configRows)
                                                                                                                                                                                                                                                                                                                                                          if (configError) {
                                                                                                                                                                                                                                                                                                                                                                console.error('[onboarding] config insert error:', configError)
                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                        // 4. Insert tenant_members (skip members with no name if solo type and name is empty)
                                                                                                                                                                                                                                                                                                                                                                            const memberRows = members.members
                                                                                                                                                                                                                                                                                                                                                                                  .filter((m) => m.name.trim().length > 0)
                                                                                                                                                                                                                                                                                                                                                                                        .map((m, i) => ({
                                                                                                                                                                                                                                                                                                                                                                                                tenant_id: tenantId,
                                                                                                                                                                                                                                                                                                                                                                                                        slug: m.name.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, ''),
                                                                                                                                                                                                                                                                                                                                                                                                                name: m.name.trim(),
                                                                                                                                                                                                                                                                                                                                                                                                                        accent_color: m.color,
                                                                                                                                                                                                                                                                                                                                                                                                                                display_order: i,
                                                                                                                                                                                                                                                                                                                                                                                                                                      }))

                                                                                                                                                                                                                                                                                                                                                                                                                                          if (memberRows.length > 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                const { error: membersError } = await supabase.from('tenant_members').insert(memberRows)
                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (membersError) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                              console.error('[onboarding] members insert error:', membersError)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // 5. Insert flock_accounts row
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const { error: accountError } = await supabase.from('flock_accounts').insert({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      auth_user_id: account.userId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            full_name: account.fullName,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  email: account.email,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        tenant_id: tenantId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (accountError) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.error('[onboarding] flock_accounts insert error:', accountError)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // 6. Add subdomain via Vercel API
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const vercelResult = await addSubdomain(community.slug)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (!vercelResult.ok) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Non-fatal — log but don't fail the request. DNS may take a moment.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  console.error('[onboarding] Vercel subdomain error:', vercelResult.error)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const redirectUrl = `https://${community.slug}.fans-flock.com?welcome=1`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return NextResponse.json({ redirectUrl }, { status: 200 })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.error('[onboarding] unexpected error:', err)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return NextResponse.json({ error: 'An unexpected error occurred.' }, { status: 500 })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }