'use client'

import { useState } from 'react'
import Step1Account from './Step1Account'
import Step2Community from './Step2Community'
import Step3Branding from './Step3Branding'
import Step4Members from './Step4Members'

export interface AccountData {
  email: string
    password: string
      fullName: string
        userId?: string
        }

        export interface CommunityData {
          communityName: string
            slug: string
              tagline: string
              }

              export interface BrandingData {
                primaryColor: string
                  secondaryColor: string
                  }

                  export interface MemberEntry {
                    name: string
                      color: string
                      }

                      export interface MembersData {
                        actType: 'solo' | 'band'
                          members: MemberEntry[]
                          }

                          export interface OnboardingState {
                            account: AccountData
                              community: CommunityData
                                branding: BrandingData
                                  members: MembersData
                                  }

                                  const STEPS = [
                                    { label: 'Account' },
                                      { label: 'Community' },
                                        { label: 'Branding' },
                                          { label: 'Members' },
                                          ]

                                          const initialState: OnboardingState = {
                                            account: { email: '', password: '', fullName: '' },
                                              community: { communityName: '', slug: '', tagline: '' },
                                                branding: { primaryColor: '#C0392B', secondaryColor: '#FADADD' },
                                                  members: { actType: 'solo', members: [{ name: '', color: '#C0392B' }] },
                                                  }

                                                  export default function OnboardingFlow() {
                                                    const [step, setStep] = useState(1)
                                                      const [data, setData] = useState<OnboardingState>(initialState)
                                                        const [submitting, setSubmitting] = useState(false)
                                                          const [fatalError, setFatalError] = useState<string | null>(null)

                                                            function updateAccount(patch: Partial<AccountData>) {
                                                                setData((d) => ({ ...d, account: { ...d.account, ...patch } }))
                                                                  }

                                                                    function updateCommunity(patch: Partial<CommunityData>) {
                                                                        setData((d) => ({ ...d, community: { ...d.community, ...patch } }))
                                                                          }

                                                                            function updateBranding(patch: Partial<BrandingData>) {
                                                                                setData((d) => ({ ...d, branding: { ...d.branding, ...patch } }))
                                                                                  }

                                                                                    function updateMembers(patch: Partial<MembersData>) {
                                                                                        setData((d) => ({ ...d, members: { ...d.members, ...patch } }))
                                                                                          }

                                                                                            async function handleComplete() {
                                                                                                setSubmitting(true)
                                                                                                    setFatalError(null)
                                                                                                        try {
                                                                                                              const res = await fetch('/api/onboarding/complete', {
                                                                                                                      method: 'POST',
                                                                                                                              headers: { 'Content-Type': 'application/json' },
                                                                                                                                      body: JSON.stringify(data),
                                                                                                                                            })
                                                                                                                                                  const json = (await res.json()) as { redirectUrl?: string; error?: string }
                                                                                                                                                        if (!res.ok) {
                                                                                                                                                                setFatalError(json.error ?? 'Something went wrong. Please try again.')
                                                                                                                                                                        setSubmitting(false)
                                                                                                                                                                                return
                                                                                                                                                                                      }
                                                                                                                                                                                            if (json.redirectUrl) {
                                                                                                                                                                                                    window.location.href = json.redirectUrl
                                                                                                                                                                                                          }
                                                                                                                                                                                                              } catch {
                                                                                                                                                                                                                    setFatalError('Network error — please check your connection and try again.')
                                                                                                                                                                                                                          setSubmitting(false)
                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                  return (
                                                                                                                                                                                                                                      <div className="onboarding-wrap">
                                                                                                                                                                                                                                            {/* Progress bar */}
                                                                                                                                                                                                                                                  <div className="onboarding-progress" aria-label="Onboarding progress">
                                                                                                                                                                                                                                                          {STEPS.map((s, i) => (
                                                                                                                                                                                                                                                                    <div
                                                                                                                                                                                                                                                                                key={s.label}
                                                                                                                                                                                                                                                                                            className={`onboarding-progress__step${i + 1 < step ? ' done' : ''}${i + 1 === step ? ' active' : ''}`}
                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                  <span className="onboarding-progress__dot">{i + 1 < step ? '✓' : i + 1}</span>
                                                                                                                                                                                                                                                                                                                              <span className="onboarding-progress__label">{s.label}</span>
                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                            {/* Step panels */}
                                                                                                                                                                                                                                                                                                                                                                  {step === 1 && (
                                                                                                                                                                                                                                                                                                                                                                          <Step1Account
                                                                                                                                                                                                                                                                                                                                                                                    data={data.account}
                                                                                                                                                                                                                                                                                                                                                                                              onChange={updateAccount}
                                                                                                                                                                                                                                                                                                                                                                                                        onNext={(userId: string) => {
                                                                                                                                                                                                                                                                                                                                                                                                                    updateAccount({ userId })
                                                                                                                                                                                                                                                                                                                                                                                                                                setStep(2)
                                                                                                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                              {step === 2 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Step2Community
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                data={data.community}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onChange={updateCommunity}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onBack={() => setStep(1)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onNext={() => setStep(3)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {step === 3 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Step3Branding
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    data={data.branding}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              communityName={data.community.communityName}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onChange={updateBranding}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onBack={() => setStep(2)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onNext={() => setStep(4)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {step === 4 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Step4Members
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  data={data.members}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onChange={updateMembers}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onBack={() => setStep(3)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onComplete={handleComplete}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          submitting={submitting}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {fatalError && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="onboarding-fatal-error" role="alert">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {fatalError}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }