'use client'

import { useState, type FormEvent } from 'react'
import { createBrowserClient } from '@supabase/ssr'
import type { AccountData } from './OnboardingFlow'

interface Props {
  data: AccountData
    onChange: (patch: Partial<AccountData>) => void
      onNext: (userId: string) => void
      }

      export default function Step1Account({ data, onChange, onNext }: Props) {
        const [loading, setLoading] = useState(false)
          const [error, setError] = useState<string | null>(null)

            async function handleSubmit(e: FormEvent) {
                e.preventDefault()
                    setError(null)
                        setLoading(true)

                            const supabase = createBrowserClient(
                                  process.env.NEXT_PUBLIC_SUPABASE_URL!,
                                        process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
                                            )

                                                const { data: authData, error: authError } = await supabase.auth.signUp({
                                                      email: data.email,
                                                            password: data.password,
                                                                  options: {
                                                                          data: { full_name: data.fullName },
                                                                                },
                                                                                    })

                                                                                        if (authError) {
                                                                                              setError(authError.message)
                                                                                                    setLoading(false)
                                                                                                          return
                                                                                                              }

                                                                                                                  if (!authData.user) {
                                                                                                                        setError('Account created — please check your email to confirm, then return here.')
                                                                                                                              setLoading(false)
                                                                                                                                    return
                                                                                                                                        }

                                                                                                                                            setLoading(false)
                                                                                                                                                onNext(authData.user.id)
                                                                                                                                                  }

                                                                                                                                                    return (
                                                                                                                                                        <form className="onboarding-step" onSubmit={handleSubmit} noValidate>
                                                                                                                                                              <div className="onboarding-step__header">
                                                                                                                                                                      <h1 className="onboarding-step__title">Create your account</h1>
                                                                                                                                                                              <p className="onboarding-step__sub">You&apos;ll use this to log in and manage your community.</p>
                                                                                                                                                                                    </div>

                                                                                                                                                                                          <div className="field-group">
                                                                                                                                                                                                  <label htmlFor="ob-fullname" className="field-label">
                                                                                                                                                                                                            Full name
                                                                                                                                                                                                                    </label>
                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                      id="ob-fullname"
                                                                                                                                                                                                                                                type="text"
                                                                                                                                                                                                                                                          className="field-input"
                                                                                                                                                                                                                                                                    autoComplete="name"
                                                                                                                                                                                                                                                                              required
                                                                                                                                                                                                                                                                                        value={data.fullName}
                                                                                                                                                                                                                                                                                                  onChange={(e) => onChange({ fullName: e.target.value })}
                                                                                                                                                                                                                                                                                                            placeholder="Your name"
                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                <div className="field-group">
                                                                                                                                                                                                                                                                                                                                        <label htmlFor="ob-email" className="field-label">
                                                                                                                                                                                                                                                                                                                                                  Email
                                                                                                                                                                                                                                                                                                                                                          </label>
                                                                                                                                                                                                                                                                                                                                                                  <input
                                                                                                                                                                                                                                                                                                                                                                            id="ob-email"
                                                                                                                                                                                                                                                                                                                                                                                      type="email"
                                                                                                                                                                                                                                                                                                                                                                                                className="field-input"
                                                                                                                                                                                                                                                                                                                                                                                                          autoComplete="email"
                                                                                                                                                                                                                                                                                                                                                                                                                    required
                                                                                                                                                                                                                                                                                                                                                                                                                              value={data.email}
                                                                                                                                                                                                                                                                                                                                                                                                                                        onChange={(e) => onChange({ email: e.target.value })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                  placeholder="you@example.com"
                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="field-group">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <label htmlFor="ob-password" className="field-label">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Password
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  id="ob-password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            type="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="field-input"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                autoComplete="new-password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    minLength={8}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              value={data.password}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onChange={(e) => onChange({ password: e.target.value })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  placeholder="At least 8 characters"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {error && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="field-error" role="alert">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {error}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button type="submit" className="btn-primary btn-full" disabled={loading}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {loading ? 'Creating account…' : 'Continue'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }