'use client'

import { useState, useEffect, type FormEvent } from 'react'
import { createBrowserClient } from '@supabase/ssr'
import type { Database } from '@/types/supabase'
import type { CommunityData } from './OnboardingFlow'

interface Props {
  data: CommunityData
    onChange: (patch: Partial<CommunityData>) => void
      onBack: () => void
        onNext: () => void
        }

        function toSlug(str: string): string {
          return str
              .toLowerCase()
                  .replace(/[^a-z0-9\s-]/g, '')
                      .replace(/\s+/g, '-')
                          .replace(/-+/g, '-')
                              .replace(/^-|-$/g, '')
                              }

                              export default function Step2Community({ data, onChange, onBack, onNext }: Props) {
                                const [slugEdited, setSlugEdited] = useState(false)
                                  const [checking, setChecking] = useState(false)
                                    const [slugAvailable, setSlugAvailable] = useState<boolean | null>(null)
                                      const [error, setError] = useState<string | null>(null)

                                        useEffect(() => {
                                            if (!slugEdited && data.communityName) {
                                                  onChange({ slug: toSlug(data.communityName) })
                                                      }
                                                        }, [data.communityName, slugEdited, onChange])

                                                          async function checkSlug(slug: string) {
                                                              if (!slug) { setSlugAvailable(null); return }
                                                                  setChecking(true)
                                                                      const supabase = createBrowserClient<Database>(
                                                                            process.env.NEXT_PUBLIC_SUPABASE_URL!,
                                                                                  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
                                                                                      )
                                                                                          const { data: existing } = await supabase
                                                                                                .from('tenants').select('id').eq('slug', slug).maybeSingle()
                                                                                                    setSlugAvailable(existing === null)
                                                                                                        setChecking(false)
                                                                                                          }

                                                                                                            function handleSlugChange(value: string) {
                                                                                                                const clean = toSlug(value)
                                                                                                                    setSlugEdited(true)
                                                                                                                        setSlugAvailable(null)
                                                                                                                            onChange({ slug: clean })
                                                                                                                              }

                                                                                                                                async function handleSubmit(e: FormEvent) {
                                                                                                                                    e.preventDefault()
                                                                                                                                        setError(null)
                                                                                                                                            if (!data.communityName.trim()) { setError('Please enter a community name.'); return }
                                                                                                                                                const slugRegex = /^[a-z0-9][a-z0-9-]{1,48}[a-z0-9]$/
                                                                                                                                                    if (!slugRegex.test(data.slug)) {
                                                                                                                                                          setError('Slug must be 3-50 lowercase characters and hyphens.')
                                                                                                                                                                return
                                                                                                                                                                    }
                                                                                                                                                                        setChecking(true)
                                                                                                                                                                            const supabase = createBrowserClient<Database>(
                                                                                                                                                                                  process.env.NEXT_PUBLIC_SUPABASE_URL!,
                                                                                                                                                                                        process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
                                                                                                                                                                                            )
                                                                                                                                                                                                const { data: existing } = await supabase
                                                                                                                                                                                                      .from('tenants').select('id').eq('slug', data.slug).maybeSingle()
                                                                                                                                                                                                          setChecking(false)
                                                                                                                                                                                                              if (existing !== null) {
                                                                                                                                                                                                                    setError(`Sorry, "${data.slug}" is already taken.`)
                                                                                                                                                                                                                          setSlugAvailable(false)
                                                                                                                                                                                                                                return
                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                        setSlugAvailable(true)
                                                                                                                                                                                                                                            onNext()
                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                return (
                                                                                                                                                                                                                                                    <form className="onboarding-step" onSubmit={handleSubmit} noValidate>
                                                                                                                                                                                                                                                          <div className="onboarding-step__header">
                                                                                                                                                                                                                                                                  <h1 className="onboarding-step__title">Name your community</h1>
                                                                                                                                                                                                                                                                          <p className="onboarding-step__sub">
                                                                                                                                                                                                                                                                                    This becomes your fan site at <strong>your-slug.fans-flock.com</strong>.
                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                        <div className="field-group">
                                                                                                                                                                                                                                                                                                                <label htmlFor="ob-community-name" className="field-label">Community name</label>
                                                                                                                                                                                                                                                                                                                        <input
                                                                                                                                                                                                                                                                                                                                  id="ob-community-name" type="text" className="field-input" required
                                                                                                                                                                                                                                                                                                                                            value={data.communityName}
                                                                                                                                                                                                                                                                                                                                                      onChange={(e) => onChange({ communityName: e.target.value })}
                                                                                                                                                                                                                                                                                                                                                                placeholder="e.g. The Stamps"
                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                    <div className="field-group">
                                                                                                                                                                                                                                                                                                                                                                                            <label htmlFor="ob-slug" className="field-label">URL slug</label>
                                                                                                                                                                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                                                                                                                                                                              id="ob-slug" type="text" required
                                                                                                                                                                                                                                                                                                                                                                                                                        className={`field-input${slugAvailable === false ? ' field-input--error' : slugAvailable === true ? ' field-input--ok' : ''}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                  value={data.slug}
                                                                                                                                                                                                                                                                                                                                                                                                                                            onChange={(e) => handleSlugChange(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                      onBlur={() => checkSlug(data.slug)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                placeholder="the-stamps"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="field-hint">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {checking ? 'Checking availability…'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      : slugAvailable === true ? `\u2713 ${data.slug}.fans-flock.com is available`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  : slugAvailable === false ? `\u2717 That slug is already taken`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              : data.slug ? `Preview: ${data.slug}.fans-flock.com`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          : 'Only lowercase letters, numbers, and hyphens'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="field-group">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <label htmlFor="ob-tagline" className="field-label">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Tagline <span className="field-label--optional">(optional)</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          id="ob-tagline" type="text" className="field-input" maxLength={120}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    value={data.tagline}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onChange={(e) => onChange({ tagline: e.target.value })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        placeholder="A short description of your community"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {error && <p className="field-error" role="alert">{error}</p>}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="onboarding-step__actions">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button type="button" className="btn-ghost" onClick={onBack}>Back</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button type="submit" className="btn-primary" disabled={checking}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {checking ? 'Checking\u2026' : 'Continue'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }