'use client'

import type { MembersData, MemberEntry } from './OnboardingFlow'

interface Props {
  data: MembersData
    onChange: (patch: Partial<MembersData>) => void
      onBack: () => void
        onComplete: () => void
          submitting: boolean
          }

          const MAX_MEMBERS = 6
          const DEFAULT_COLORS = ['#C0392B', '#2980B9', '#27AE60', '#8E44AD', '#E67E22', '#16A085']

          export default function Step4Members({ data, onChange, onBack, onComplete, submitting }: Props) {
            function setActType(actType: 'solo' | 'band') {
                if (actType === 'solo') {
                      onChange({ actType, members: [{ name: data.members[0]?.name ?? '', color: DEFAULT_COLORS[0] }] })
                          } else {
                                onChange({ actType, members: data.members.length > 1 ? data.members : [
                                        { name: data.members[0]?.name ?? '', color: DEFAULT_COLORS[0] },
                                                { name: '', color: DEFAULT_COLORS[1] },
                                                      ] })
                                                          }
                                                            }

                                                              function updateMember(index: number, patch: Partial<MemberEntry>) {
                                                                  const updated = data.members.map((m, i) => i === index ? { ...m, ...patch } : m)
                                                                      onChange({ members: updated })
                                                                        }

                                                                          function addMember() {
                                                                              if (data.members.length >= MAX_MEMBERS) return
                                                                                  onChange({
                                                                                        members: [...data.members, { name: '', color: DEFAULT_COLORS[data.members.length] ?? '#888888' }],
                                                                                            })
                                                                                              }

                                                                                                function removeMember(index: number) {
                                                                                                    if (data.members.length <= 2) return
                                                                                                        onChange({ members: data.members.filter((_, i) => i !== index) })
                                                                                                          }

                                                                                                            return (
                                                                                                                <div className="onboarding-step">
                                                                                                                      <div className="onboarding-step__header">
                                                                                                                              <h1 className="onboarding-step__title">Who&apos;s in your act?</h1>
                                                                                                                                      <p className="onboarding-step__sub">This helps us personalise your community page.</p>
                                                                                                                                            </div>

                                                                                                                                                  <div className="field-group">
                                                                                                                                                          <p className="field-label">Act type</p>
                                                                                                                                                                  <div className="act-type-toggle">
                                                                                                                                                                            <button
                                                                                                                                                                                        type="button"
                                                                                                                                                                                                    className={`act-type-btn${data.actType === 'solo' ? ' active' : ''}`}
                                                                                                                                                                                                                onClick={() => setActType('solo')}
                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                      Solo artist
                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                      type="button"
                                                                                                                                                                                                                                                                                  className={`act-type-btn${data.actType === 'band' ? ' active' : ''}`}
                                                                                                                                                                                                                                                                                              onClick={() => setActType('band')}
                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                    Band
                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                  <div className="members-list">
                                                                                                                                                                                                                                                                                                                                                          {data.members.map((member, i) => (
                                                                                                                                                                                                                                                                                                                                                                    <div key={i} className="member-row">
                                                                                                                                                                                                                                                                                                                                                                                <div className="color-picker-row">
                                                                                                                                                                                                                                                                                                                                                                                              <input
                                                                                                                                                                                                                                                                                                                                                                                                              type="color"
                                                                                                                                                                                                                                                                                                                                                                                                                              className="color-swatch-input"
                                                                                                                                                                                                                                                                                                                                                                                                                                              value={member.color}
                                                                                                                                                                                                                                                                                                                                                                                                                                                              onChange={(e) => updateMember(i, { color: e.target.value })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              aria-label={`Colour for member ${i + 1}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          type="text"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="field-input"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          placeholder={data.actType === 'solo' ? 'Your name' : `Member ${i + 1} name`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          value={member.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onChange={(e) => updateMember(i, { name: e.target.value })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {data.actType === 'band' && data.members.length > 2 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              type="button"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="member-remove-btn"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={() => removeMember(i)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              aria-label={`Remove member ${i + 1}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            &times;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {data.actType === 'band' && data.members.length < MAX_MEMBERS && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button type="button" className="btn-ghost btn-add-member" onClick={addMember}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      + Add member
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="onboarding-step__actions">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button type="button" className="btn-ghost" onClick={onBack} disabled={submitting}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Back
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="onboarding-step__actions-right">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  type="button"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="btn-ghost btn-skip"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={onComplete}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      disabled={submitting}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Skip
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            type="button"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="btn-primary"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onClick={onComplete}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                disabled={submitting}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {submitting ? 'Creating your community\u2026' : 'Launch my community'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }